### ISSUE TITLE
Update post with redirect to the /drafts page

### ISSUE THREAD

**Issue by robots4life** [sonylomo/demo-sveltekit#8]
https://github.com/sonylomo/demo-sveltekit/blob/57ff2aae16d9945c6bf90846a9be548b6582ef89/src/routes/create/%2Bpage.server.ts#LL29C35-L29C35

https://www.prisma.io/blog/sveltekit-prisma-kvCOEoeQlC#create-create-a-new-post-in-your-database

Please update this section of the post with the correct redirect to the `/dratfs` page, thank you.

**Comment by ruheni** [comment]
👋 

Thanks for raising this. We've resolved it!
